# applies to podtato-head-entry deployment only
ingress:
  className: nginx
  annotations:
    external-dns.alpha.kubernetes.io/ttl: "60"
    cert-manager.io/cluster-issuer: default-issuer
  hosts:
    - host: kubrix-demo-app-qa.demo-app.kubrix.cape.rocks
      paths:
        - path: /
          pathType: ImplementationSpecific
